### ISSUE TITLE
Problem With Https

### ISSUE THREAD

**Issue by riefive** [Kynec/digest-ajax#1]
I have a problem with **https** protocol, any solution?

**Comment by Kynec** [comment]
Are you making a CORS request? If so, the WWW-Authenticate header must be present in the Access-Control-Expose-Headers returned by the server.

See http://stackoverflow.com/questions/4369987/jquery-getresponseheader-always-returns-undefined for an explanation.

**Comment by riefive** [comment]
Sorry for late response. yes, i made cors. Trims for your explation. Now, i have no problem with ajax request.
